# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD - rawg-server

on: # when to run the workflow
  push: # when code is pushed to the repository
    branches:
      - main # only run on the main branch
    paths:
      - "rawg-server/**" # only follow changes in rawg-server directory
      - ".github/workflows/ci-cd_rawg-server.yml" #and changes in workflow file
  workflow_dispatch: # allows you to run the workflow manually

jobs:
  build: # the build job
    runs-on: ubuntu-latest # the type of runner to use
    permissions:
      contents: read #This is required for actions/checkout

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4 # copy the repository to the runner

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -u"testuser" -p"testpass" --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: npm install, build, and test # go to rawg-server directory
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: testuser
          DB_PASSWORD: testpass
          DB_NAME: testdb
        run: |
          cd rawg-server 
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment # zip the rawg-server directory
        run: |
          cd rawg-server
          zip -r ../release.zip .

      - name: Upload artifact for deployment job # upload the zip file
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy: # the deploy job
    runs-on: ubuntu-latest # the type of runner to use
    needs: build # the deploy job depends on the build job to finish first
    environment: # the environment to deploy to
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job # download the zip file
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App" # deploy the release artifact to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rawg-server"
          slot-name: "Production" # the slot to deploy to
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1B05ED26C75A42108A5C4903CF4C7F83 }}
