name: Client CI

on:
  push:
    paths:
      - "rawg-client/**"
      - ".github/workflows/client-ci.yml"
  pull_request:
    paths:
      - "rawg-client/**"
      - ".github/workflows/client-ci.yml"
  workflow_dispatch: # allows you to run the workflow manually

jobs:
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rawg-client
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run client tests
        run: npm test
