name: Server CI

# Run on all branches
on:
  push:
    paths:
      - "rawg-server/**"
  pull_request:
    paths:
      - "rawg-server/**"
  workflow_dispatch: # allows you to run the workflow manually

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rawg-server
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run server tests
        run: npm test
