name: Server CI

# Run on all branches
on:
  push:
    paths:
      - "rawg-server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    paths:
      - "rawg-server/**"
      - ".github/workflows/server-ci.yml"
  workflow_dispatch: # allows you to run the workflow manually

jobs:
  test-server:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0-debian
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysql -uroot -prootpassword -e 'SELECT 1'"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=10
    defaults:
      run:
        working-directory: ./rawg-server
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          DATABASE_URL: mysql://root:rootpassword@127.0.0.1:3307/testdb # Updated to use a single connection string
          JWT_SECRET: dev_secret
        run: npm test
