name: Server CI

# Run on all branches
on:
  push:
    paths:
      - "rawg-server/**"
  pull_request:
    paths:
      - "rawg-server/**"
  workflow_dispatch: # allows you to run the workflow manually

jobs:
  test-server:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    defaults:
      run:
        working-directory: ./rawg-server
    steps:
      - uses: actions/checkout@v3
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -u"testuser" -p"testpass" --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
      - name: Install dependencies
        run: npm install
      - name: Run server tests
        env:
          DATABASE_URL: mysql://testuser:testpass@127.0.0.1:3306/testdb
        run: npm test
